import { defineConfig } from 'vitest/config';
import path from 'node:path';
import fs from 'node:fs';

/**
 * Vite plugin that resolves .js/.mjs/.cjs imports to .ts when the
 * original file doesn't exist on disk.  This handles CJS require()
 * calls in test files that reference source modules renamed from
 * .js to .ts during the TypeScript conversion.
 */
function resolveJsToTs() {
  const jsExts = ['.js', '.mjs', '.cjs'];
  return {
    name: 'resolve-js-to-ts',
    enforce: 'pre',
    resolveId(source, importer) {
      if (!importer || /node_modules/.test(source)) return null;
      if (!source.startsWith('.') && !path.isAbsolute(source)) return null;

      const dir = path.dirname(importer);

      // Case 1: explicit .js extension → try .ts
      if (source.endsWith('.js')) {
        const resolved = path.resolve(dir, source);
        if (fs.existsSync(resolved)) return null;
        const tsPath = resolved.replace(/\.js$/, '.ts');
        if (fs.existsSync(tsPath)) return tsPath;
        return null;
      }

      // Case 2: no extension (bare require) → try .ts first, then .js
      const hasExt =
        jsExts.some((e) => source.endsWith(e)) ||
        source.endsWith('.ts') ||
        source.endsWith('.json');
      if (!hasExt) {
        const base = path.resolve(dir, source);
        const tsPath = base + '.ts';
        if (fs.existsSync(tsPath)) return tsPath;
      }

      return null;
    },
  };
}

export default defineConfig({
  plugins: [resolveJsToTs()],
  resolve: {
    extensions: ['.ts', '.js', '.mjs', '.cjs', '.json'],
  },
  test: {
    globals: true,
    fileParallelism: false,
    deps: {
      inline: [/./],
    },
    setupFiles: ['tests/setup-require-hook.js'],
    include: ['tests/**/*.test.{js,ts}'],
    exclude: [
      '**/node_modules/**',
      'tests/integration/dispatcher-reflection-loop.test.js',
      'tests/integration/git-adapter.integration.test.js',
      'tests/integration/testing-adapter.integration.test.js',
      'tests/unit/action-proposer.test.js',
      'tests/unit/adapter-result-cache.test.js',
      'tests/unit/agency-executor.test.js',
      'tests/unit/agent-execution-service.test.js',
      'tests/unit/agent-registry.test.js',
      'tests/unit/agent-runtime-adapter.test.js',
      'tests/unit/agent-schema.test.js',
      'tests/unit/analytics-observability.test.js',
      'tests/unit/analytics-routes.test.js',
      'tests/unit/approvals-routes.test.js',
      'tests/unit/architecture-fitness-c3.test.js',
      'tests/unit/artifact-registration.test.js',
      'tests/unit/artifacts.test.js',
      'tests/unit/audit-trail.test.js',
      'tests/unit/auth-guard.test.js',
      'tests/unit/auth.test.js',
      'tests/unit/azure-devops-provider-backend.test.js',
      'tests/unit/backup-strategy.test.js',
      'tests/unit/bootstrap.test.js',
      'tests/unit/bullmq-queue.test.js',
      'tests/unit/bullmq-scalability.test.js',
      'tests/unit/cache.test.js',
      'tests/unit/ci-adapter.test.js',
      'tests/unit/chat-grounding-quality.test.js',
      'tests/unit/cli.test.js',
      'tests/unit/config.test.js',
      'tests/unit/context-adapter.test.js',
      'tests/unit/context-budgeter.test.js',
      'tests/unit/contract-compliance.test.js',
      'tests/unit/contrast.test.js',
      'tests/unit/dashboard-service.test.js',
      'tests/unit/deliverable-quality.test.js',
      'tests/unit/dispatcher.test.js',
      'tests/unit/doc-drift.test.js',
      'tests/unit/drift-detector.test.js',
      'tests/unit/email-templates.test.js',
      'tests/unit/enforcing-governance.test.js',
      'tests/unit/engine-hooks.test.js',
      'tests/unit/engine-recovery-safety.test.js',
      'tests/unit/engine.test.js',
      'tests/unit/error-catalog.test.js',
      'tests/unit/error-recovery.test.js',
      'tests/unit/errors.test.js',
      'tests/unit/example.test.js',
      'tests/unit/execution-mode-plan.test.js',
      'tests/unit/execution-mode.test.js',
      'tests/unit/file-lock.test.js',
      'tests/unit/flow-loader.test.js',
      'tests/unit/flow-schema.test.js',
      'tests/unit/gate-validator.test.js',
      'tests/unit/git-backend-contract.test.js',
      'tests/unit/git-backend-router.test.js',
      'tests/unit/git-browserfs-adapter.test.js',
      'tests/unit/git-credential-store.test.js',
      'tests/unit/git-service.test.js',
      'tests/unit/git-shell-call-guard.test.js',
      'tests/unit/github-provider-backend.test.js',
      'tests/unit/github-state-snapshot.test.js',
      'tests/unit/governance-docs.test.js',
      'tests/unit/governance-mode.test.js',
      'tests/unit/governance-service.test.js',
      'tests/unit/governance.test.js',
      'tests/unit/help-service.test.js',
      'tests/unit/hybrid-executor.test.js',
      'tests/unit/intent-classifier.test.js',
      'tests/unit/isomorphic-git-backend.test.js',
      'tests/unit/job-queue.test.js',
      'tests/unit/knowledge-provider.test.js',
      'tests/unit/lesson-promotion.test.js',
      'tests/unit/m2m-api-policy.test.js',
      'tests/unit/matomo-analytics.test.js',
      'tests/unit/mcp-governance-cli.test.js',
      'tests/unit/mcp-governance-factories.test.js',
      'tests/unit/mcp-governance-health-monitor.test.js',
      'tests/unit/mcp-governance-service.test.js',
      'tests/unit/mcp-server.test.js',
      'tests/unit/memory-access-policy.test.js',
      'tests/unit/memory-namespace.test.js',
      'tests/unit/metrics-collector.test.js',
      'tests/unit/metrics-dashboard.test.js',
      'tests/unit/middleware.test.js',
      'tests/unit/misc-analytics.test.js',
      'tests/unit/misc-export.test.js',
      'tests/unit/misc-health.test.js',
      'tests/unit/misc-observability.test.js',
      'tests/unit/misc-static.test.js',
      'tests/unit/models-corruption.test.js',
      'tests/unit/models-edge.test.js',
      'tests/unit/models-m32-edge.test.js',
      'tests/unit/models-session.test.js',
      'tests/unit/models.test.js',
      'tests/unit/native-git-backend.test.js',
      'tests/unit/non-local-api-guard.test.js',
      'tests/unit/observability-dora.test.js',
      'tests/unit/observability.test.js',
      'tests/unit/openapi-spec.test.js',
      'tests/unit/orchestrator-routes.test.js',
      'tests/unit/outcome-tracking-service.test.js',
      'tests/unit/p2-adapters-coverage.test.js',
      'tests/unit/pattern-analysis-service.test.js',
      'tests/unit/persistence/migrate-storage.test.js',
      'tests/unit/persistence/storage-contract.test.js',
      'tests/unit/persistent-queue.test.js',
      'tests/unit/pilot-readiness.test.js',
      'tests/unit/plugins.test.js',
      'tests/unit/policy-evaluator.test.js',
      'tests/unit/policy-service.test.js',
      'tests/unit/prompt-template-snapshots.test.js',
      'tests/unit/provider-registry-direct.test.js',
      'tests/unit/providers-behavior.test.js',
      'tests/unit/rag-code-chunker.test.js',
      'tests/unit/rag-embedding-provider.test.js',
      'tests/unit/rag-grounding-service.test.js',
      'tests/unit/rag-incremental.test.js',
      'tests/unit/rag-indexer.test.js',
      'tests/unit/rag-markdown-chunker.test.js',
      'tests/unit/rag-store.test.js',
      'tests/unit/rag-types.test.js',
      'tests/unit/rate-limit-plugin.test.js',
      'tests/unit/rate-limiter.test.js',
      'tests/unit/reasoning-collaboration.test.ts',
      'tests/unit/redis.test.js',
      'tests/unit/repo-indexer.test.js',
      'tests/unit/retrieval-api.test.js',
      'tests/unit/route-registration-manifest.test.js',
      'tests/unit/route-schemas.test.js',
      'tests/unit/router.test.js',
      'tests/unit/routes-agents-execute.test.js',
      'tests/unit/routes-agents.test.js',
      'tests/unit/routes-artifacts.test.js',
      'tests/unit/routes-auth.test.js',
      'tests/unit/routes-chat.test.js',
      'tests/unit/routes-cockpit-provenance.test.js',
      'tests/unit/routes-commands.test.js',
      'tests/unit/routes-dashboard.test.js',
      'tests/unit/routes-decisions.test.js',
      'tests/unit/routes-drift.test.js',
      'tests/unit/routes-git.test.js',
      'tests/unit/routes-help.test.js',
      'tests/unit/routes-jobs.test.js',
      'tests/unit/routes-mcp.test.js',
      'tests/unit/routes-milestones.test.js',
      'tests/unit/routes-misc-functions.test.js',
      'tests/unit/routes-orchestrator.test.js',
      'tests/unit/routes-policies.test.js',
      'tests/unit/routes-progress.test.js',
      'tests/unit/routes-rag.test.js',
      'tests/unit/routes-reasoning-collaboration.test.ts',
      'tests/unit/routes-sessions.test.js',
      'tests/unit/routes-subscribe.test.js',
      'tests/unit/routes-task-assembly.test.js',
      'tests/unit/routes-workspaces.test.js',
      'tests/unit/runtime-adapter-modules.test.js',
      'tests/unit/runtime-profiles.test.js',
      'tests/unit/runtime-scaffold.test.js',
      'tests/unit/sanitization.test.js',
      'tests/unit/schemas.test.js',
      'tests/unit/sdlc-adapters.test.js',
      'tests/unit/sdlc-artifacts.test.js',
      'tests/unit/sdlc-entities.test.js',
      'tests/unit/sdlc-governance.test.js',
      'tests/unit/sdlc-lifecycle.test.js',
      'tests/unit/sdlc-observability.test.js',
      'tests/unit/sdlc-traceability.test.js',
      'tests/unit/secret-utils.test.js',
      'tests/unit/security-adapter-helpers.test.js',
      'tests/unit/security-adapter-runtime.test.js',
      'tests/unit/security-adapter.test.js',
      'tests/unit/security-audit.test.js',
      'tests/unit/semantic-memory.test.js',
      'tests/unit/server-rag-freshness.test.js',
      'tests/unit/server-startup-validation.test.js',
      'tests/unit/server-storage-enforcement.test.js',
      'tests/unit/server.test.js',
      'tests/unit/session-help-service.test.js',
      'tests/unit/session-service.test.js',
      'tests/unit/session-state-resolver.test.js',
      'tests/unit/session-tracker.test.js',
      'tests/unit/shell-executor.test.js',
      'tests/unit/social-cards.test.js',
      'tests/unit/sqlite-concurrency.test.js',
      'tests/unit/sse-manager.test.js',
      'tests/unit/state-machine.test.js',
      'tests/unit/state-persistence.test.js',
      'tests/unit/static-handler.test.js',
      'tests/unit/store-async.test.js',
      'tests/unit/store.test.js',
      'tests/unit/strings.test.js',
      'tests/unit/sprint-gate.test.js',
      'tests/unit/template-loader.test.js',
      'tests/unit/testing-adapter.test.js',
      'tests/unit/tool-execution-middleware.test.js',
      'tests/unit/tool-executor.test.js',
      'tests/unit/tool-schema.test.js',
      'tests/unit/traceability.test.js',
      'tests/unit/transition-event-log.test.js',
      'tests/unit/transition-lease.test.js',
      'tests/unit/translation-validation.test.js',
      'tests/unit/transpiler.test.js',
      'tests/unit/unified-quality-gate.test.js',
      'tests/unit/utils-errors.test.js',
      'tests/unit/weblate-docker.test.js',
      'tests/unit/weblate-sync.test.js',
      'tests/unit/weblate-trial.test.js',
      'tests/unit/workload-identity-corrected.test.js',
      'tests/unit/workload-identity.test.js',
      'tests/unit/workspace-manager.test.js',
      'tests/unit/write-ahead-persistence.test.js',
    ],
    coverage: {
      provider: 'v8',
      include: [
        'src/webapp/**/*.{js,ts}',
        'platform/engine/**/*.{js,ts}',
        'platform/sdlc/**/*.{js,ts}',
      ],
      exclude: [
        'src/webapp/node_modules/**',
        'src/webapp/ui/**',
        '**/index.ts',
        '**/types.ts',
        'platform/sdlc/adapters/contracts/**',
        'platform/engine/persistence/storage-provider.ts',
        'platform/engine/jobs/job-types.ts',
        'src/webapp/start.ps1',
        'platform/engine/flows.yaml',
        '**/*.d.ts',
      ],
      reporter: ['text', 'text-summary', 'json-summary', 'json'],
      reportsDirectory: 'coverage',
    },
  },
});
