import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    globals: true,
    fileParallelism: false,
    include: [
      'tests/unit/dispatcher.test.js',
      'tests/integration/dispatcher-reflection-loop.test.js',
      'tests/unit/agent-runtime-adapter.test.js',
      'tests/unit/agent-execution-service.test.js',
      'tests/unit/error-recovery.test.js',
      'tests/unit/routes-agents-execute.test.js',
      'tests/unit/routes-agents.test.js',
      'tests/unit/job-queue.test.js',
      'tests/unit/template-loader.test.js',
      'tests/unit/reasoning-collaboration.test.ts',
      'tests/unit/routes-reasoning-collaboration.test.ts',
    ],
    coverage: {
      provider: 'istanbul',
      include: [
        'platform/engine/dispatcher.ts',
        'platform/engine/self-revision.ts',
        'platform/engine/agent-runtime-adapter.ts',
        'src/webapp/services/agent-execution-service.ts',
        'src/webapp/routes/agents.ts',
        'platform/engine/jobs/memory-queue.ts',
        'platform/engine/jobs/worker.ts',
        'platform/engine/jobs/job-metrics.ts',
        'platform/engine/template-loader.ts',
        'platform/engine/state-machine.ts',
        'platform/engine/state-persistence.ts',
        'platform/engine/cli.ts',
        'platform/engine/reasoning-profile.ts',
        'platform/engine/verifier-pass.ts',
        'platform/engine/a2a-messaging.ts',
        'platform/engine/peer-clarification.ts',
        'platform/engine/a2a-collaboration-tracer.ts',
        'src/webapp/routes/reasoning-collaboration.ts',
      ],
      exclude: [
        '**/node_modules/**',
        '**/index.ts',
        '**/types.ts',
        '**/*.d.ts',
        'platform/engine/flows.yaml',
        'platform/engine/persistence/storage-provider.ts',
        'platform/engine/jobs/job-types.ts',
      ],
      reporter: ['text', 'text-summary', 'json-summary', 'json'],
      reportsDirectory: 'coverage/migrated-istanbul',
    },
  },
});