// Copyright (c) 2026 Robert Agterhuis. MIT License.
'use strict';

/**
 * Command queue route handlers — POST/GET /api/command.
 * @module routes/commands
 * @param {object} ctx - Shared server context.
 * @returns {object} Route map { 'METHOD /path': handler }.
 */

const path = require('path');
const { getStore } = require('../store');
const models = require('../models');
const schemas = require('../schemas');
const { withFileLock } = require('../file-lock');
const { attachSecretWarnings } = require('../utils/secret-utils');
const { errorResponse } = require('../utils/errors');
const { RESPONSES: R } = require('../strings');
const {
  structuredLog,
  json,
  parseBody,
  assertString,
  sanitizeMarkdown,
  sanitizeQID,
  checkSecretsInBody,
} = require('../middleware');

const VALID_COMMANDS = [
  'CREATE',
  'CREATE BUSINESS',
  'CREATE TECH',
  'CREATE UX',
  'CREATE MARKETING',
  'CREATE SYNTHESIS',
  'AUDIT',
  'AUDIT BUSINESS',
  'AUDIT TECH',
  'AUDIT UX',
  'AUDIT MARKETING',
  'AUDIT SYNTHESIS',
  'REEVALUATE',
  'FEATURE',
  'SCOPE CHANGE',
  'HOTFIX',
  'REFRESH ONBOARDING',
  'CONTINUE',
];

const COMMAND_OPT_FIELDS = ['project', 'description', 'scope', 'brief'];
const COMMAND_OPT_LIMITS = { project: 200, description: 2000, scope: 200, brief: 200000 };

module.exports = function createCommandRoutes(ctx) {
  const { _cache, safeWriteSync, sseNotify, SESSION_DIR, COMMAND_QUEUE, BUSINESS_DOCS } = ctx;

  function validateCommandBody(body) {
    assertString(body.command, 'command', 100);
    for (const f of COMMAND_OPT_FIELDS) {
      if (body[f]) assertString(body[f], f, COMMAND_OPT_LIMITS[f]);
    }
    if (body.description) body.description = sanitizeMarkdown(sanitizeQID(body.description));
    if (body.brief) body.brief = sanitizeMarkdown(sanitizeQID(body.brief));
  }

  function isValidCommand(cmd) {
    const parts = cmd.split(/\s+/);
    return (
      VALID_COMMANDS.includes(cmd) ||
      VALID_COMMANDS.includes(parts.slice(0, 2).join(' ')) ||
      (VALID_COMMANDS.includes(parts[0]) && parts.length <= 1)
    );
  }

  function buildCommandEntry(body) {
    return {
      command: body.command.trim(),
      project: (body.project || '').trim() || null,
      description: (body.description || '').trim() || null,
      scope: (body.scope || '').trim() || null,
      requested_at: models.isoNow(),
      status: 'PENDING',
      source: 'webapp',
    };
  }

  async function saveProjectBrief(body, entry) {
    if (!body.brief || typeof body.brief !== 'string' || !body.brief.trim()) return;
    const briefCheck = schemas.validateProjectBrief(body.brief);
    if (!briefCheck.valid) return;
    getStore().mkdirp(BUSINESS_DOCS);
    const briefPath = path.join(BUSINESS_DOCS, 'project-brief.md');
    await withFileLock(briefPath, async () => {
      const briefContent =
        `# Project Brief — ${entry.project || 'Untitled'}\n\n` +
        `> Auto-generated by Command Center on ${models.isoNow()}\n\n` +
        body.brief.trim() +
        '\n';
      safeWriteSync(briefPath, briefContent);
    });
    entry.brief_saved = true;
    entry.brief_path = 'BusinessDocs/project-brief.md';
  }

  function buildClipboardText(entry) {
    let text = entry.command;
    if (entry.project) text += ' ' + entry.project;
    if (entry.description) text += ': ' + entry.description;
    return text;
  }

  function readCommandQueue() {
    if (!getStore().exists(COMMAND_QUEUE)) return [];
    try {
      const raw = JSON.parse(_cache.read(COMMAND_QUEUE));
      return Array.isArray(raw) ? raw : raw ? [raw] : [];
    } catch {
      return [];
    }
  }

  async function appendToCommandQueue(entry) {
    await withFileLock(COMMAND_QUEUE, async () => {
      const MAX_QUEUE_SIZE = 50;
      let queue = readCommandQueue();
      queue.push(entry);
      if (queue.length > MAX_QUEUE_SIZE) queue = queue.slice(-MAX_QUEUE_SIZE);
      safeWriteSync(COMMAND_QUEUE, JSON.stringify(queue, null, 2));
    });
  }

  function getLatestCommand(queue) {
    if (!queue) queue = readCommandQueue();
    return queue.length ? queue[queue.length - 1] : null;
  }

  async function apiPostCommand(req, res) {
    const body = await parseBody(req);
    validateCommandBody(body);

    const cmdSecrets = checkSecretsInBody(body, ['description', 'brief']);
    if (cmdSecrets.length > 0)
      structuredLog('warn', 'secret_pattern_in_command', {
        patterns: cmdSecrets,
        command: body.command,
      });

    const cmd = body.command.trim().toUpperCase();
    if (!isValidCommand(cmd))
      return json(res, 400, errorResponse('UNKNOWN_COMMAND', R.unknownCommand(body.command)));

    getStore().mkdirp(SESSION_DIR);
    const entry = buildCommandEntry(body);
    await saveProjectBrief(body, entry);
    entry.clipboard_text = buildClipboardText(entry);
    await appendToCommandQueue(entry);

    sseNotify('command_queued', {
      type: 'command_queued',
      command: entry.command,
      project: entry.project,
      timestamp: entry.requested_at,
    });

    const cmdResponse = {
      ok: true,
      clipboard_text: entry.clipboard_text,
      brief_saved: !!entry.brief_saved,
      message: R.commandQueued(entry.clipboard_text),
    };
    attachSecretWarnings(cmdResponse, cmdSecrets);
    json(res, 200, cmdResponse);
  }

  async function apiGetCommand(_req, res) {
    const queue = readCommandQueue();
    json(res, 200, { command: getLatestCommand(queue), queue });
  }

  // Expose helpers for cross-module use (progress needs getLatestCommand + readCommandQueue)
  const routes = {
    'POST /api/command': apiPostCommand,
    'GET /api/command': apiGetCommand,
  };
  routes._readCommandQueue = readCommandQueue;
  routes._getLatestCommand = getLatestCommand;
  return routes;
};
